### PR TITLE
Added the global ignore file option.

### PR DESCRIPTION
**Pull request by fatfisz**
This is a first step to solving the global gitignore problem: npm/npm#5673.

### CODE REVIEW

**Comment by fatfisz** [comment]
As with npm/fstream-ignore#10, there are some problems with Travis CI itself.

**Comment by fatfisz** [comment]
I've added the same .travis.yml file as in npm/fstream-ignore#10 so that the tests could run.

**Comment by fatfisz** [comment]
Anyone, please? The patch has been waiting for almost a month, and there is still no response whatsoever :(

**Comment by isaacs** [comment]
@fatfisz Hey, I'm sorry about the radio silence on this.  It's on the command line team's radar, but they haven't had a chance to merge it and run through the whole suite of tests.  We should get to this pretty soon, but I'm not sure exactly when, unfortunately.  Thanks for your patience.

**Comment by isaacs** [comment]
(The travis stuff is a known issue, as you point out.)

**Comment by fatfisz** [comment]
Thanks, in this case any response is a good response :)

**Comment by zkat** [comment]
Hey! This is on our roadmap for "soon" -- see https://github.com/npm/npm/issues/5673. Keep an eye out for a more concrete response for this in the near future. Thanks for the PR :)

**Comment by fatfisz** [comment]
Yay! :)

**Comment by fatfisz** [comment]
@zkat Relating to: https://github.com/npm/npm/issues/5673#issuecomment-197731505
I thought my PR took care of that? I'm injecting the global ignore file at the start, before any other ignore files are processed. Because the path to the ignore file should be absolute, the `addIgnoreFile` should have no trouble reading the file even if it is not contained in the project tree. Though I probably shoud have made added an appropriate test case...

**Comment by zkat** [comment]
It does, and I considered this, but I'm also not sure how I feel about adding this particular feature at the `fstream-ignore` error. Mostly because it's kinda unclear where anything is actually supposed to go in this tower. I'm still thinking of grabbing this PR (or rewriting it into something similar and crediting you with `--author`), but I wanna talk to the others on the team about what the Right Thing here is.

**Comment by fatfisz** [comment]
No problem, I just wondered if there was some sort of confusion :)

**Comment by zkat** [comment]
There's a bunch of fstream-related work that @othiym23 is doing right now, so I wanna keep holding off on features like this one until we can see what that ends up at -- there's a chance a lot about this will change in the middle-near future. Thanks for your patience!

**Comment by ELLIOTTCABLE** [comment]
Anything an outsider can do to contribute to this? The security implications alone … `:x`

**Comment by isaacs** [comment]
This library is no longer in use by supported versions of the npm CLI, and I believe should be deprecated.  I'll leave it to @zkat and @iarna to decide how best to do that.

File ignoring is now done with https://github.com/isaacs/ignore-walk

**Pull request closed without merging**
